export const cityList = [
    { cityId: 1, cityName: "강남구" },
    { cityId: 2, cityName: "강동구" },
    { cityId: 3, cityName: "강북구" },
    { cityId: 4, cityName: "강서구" },
    { cityId: 5, cityName: "관악구" },
    { cityId: 6, cityName: "광진구" },
    { cityId: 7, cityName: "구로구" },
    { cityId: 8, cityName: "금천구" },
    { cityId: 9, cityName: "노원구" },
    { cityId: 10, cityName: "도봉구" },
    { cityId: 11, cityName: "동대문구" },
    { cityId: 12, cityName: "동작구" },
    { cityId: 13, cityName: "마포구" },
    { cityId: 14, cityName: "서대문구" },
    { cityId: 15, cityName: "서초구" },
    { cityId: 16, cityName: "성동구" },
    { cityId: 17, cityName: "성북구" },
    { cityId: 18, cityName: "송파구" },
    { cityId: 19, cityName: "양천구" },
    { cityId: 20, cityName: "영등포구" },
    { cityId: 21, cityName: "용산구" },
    { cityId: 22, cityName: "은평구" },
    { cityId: 23, cityName: "종로구" },
    { cityId: 24, cityName: "중구" },
    { cityId: 25, cityName: "중랑구" }
];
